version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
     - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: "16.13"
      - checkout
      - aws-cli/setup
      - aws-elastic-beanstalk/setup

      - run:
          name: install front dep
          command: |
           npm run fe:install
      - run:
          name: install backend dep
          command: |
           npm run api:install
      - run:
          name: build front 
          command: |
            npm run fe:build
      - run:
          name: build backend
          command: |
           npm run api:build
      - run:
          name: deploy front 
          command: |
           npm run frontend:deploy
      - run:
          name: install backend deploy
          command: |
            npm run backend:deploy
      - run:
          name: install backend deploy
          command: |
           npm run backend:deploy 
      - run:
          name: install front deploy
          command: |
            npm run frontend:deploy
           
workflows:
    buildandeploy:
      jobs:
        - build:
            filters:
              branches:
                only:
                  - main
